name: Updating Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18 # optional
    - name: Creating Image and Updating
      run: |
        npm install -g pnpm
        cd frontend
        pnpm install
        pnpm run build
        cd ..
        cp /root/openui/docker-compose.yaml .
        cat docker-compose.yaml 
        echo "Moving for docker image"
        docker compose  build 
        docker compose up -d
