name: Updating Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Creating Image and Updating
      run: |
        cd backend
        docker stop $(sudo docker ps -q) || true
        docker system prune -f  || true
        docker rmi wandb/openui  || true
        docker build . -t wandb/openui --load
        docker run -d -p 7878:7878 -e OPENAI_API_KEY=${{ secrets.OPENUI_KEY }} wandb/openui
