name: Updating Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18 # optional
    - name: Creating Image and Updating
      run: |
    - uses: actions/checkout@v3
    - name: Creating Image and Updating
      run: |
        docker compose -f /root/openui/docker-compose.yaml build 
        docker compose -f /root/openui/docker-compose.yaml up -d
